#!/bin/sh

mkdir -p public/media/thumbnails
for i in public/media/Small\ JPEGS/*.jpg
do
  n=`basename "$i"`
  if [ -e "public/media/thumbnails/$n" ]
  then
    echo "Skipping $n"
  else
    echo $n
    convert "$i" -resize 200 "public/media/thumbnails/$n"
  fi
done
